version: "3"
services:
  worker:
    image: worker
    build: jil22400/dockercoins
  rng:
    image: nisozh/rng:1.0
  hasher:
    image: alexisbonnet1997/hasher
  webui:
    image: brahimhamdi/webui:1.0
    ports:
      - "8000:80"
  redis:
    image: redis
