---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: hasher-deployment
 labels:
   app: dockercoins
   tier: hasher
spec:
 replicas: 1
 selector:
   matchLabels:
     app: dockercoins
     tier: hasher
   template:
     metadata:
       labels:
         app: dockercoins
         tier: hasher
     spec:
       containers:
       - name: hasher
         image: gitlab.orsys.fr:5050/brahimhamdi/dockercoins/hasher:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: dockercoins
    tier: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockercoins
      tier: redis
  template:
    metadata:
      labels:
        app: dockercoins
        tier: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rng-deployment
  labels:
    app: dockercoins
    tier: rng
spec:
  selector:
    matchLabels:
      app: dockercoins
      tier: rng
    template:
      metadata:
        labels:
          app: dockercoins
          tier: rng
      spec:
        containers:
        - name: rng
          image: gitlab.orsys.fr:5050/brahimhamdi/dockercoins/rng:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-deployment
  labels:
    app: dockercoins
    tier: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockercoins
      tier: webui
  template:
    metadata:
      labels:
        app: dockercoins
        tier: webui
    spec:
      containers:
      - name: webui
        image: brahimhamdi/webui:1.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: dockercoins
    tier: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockercoins
      tier: worker
  template:
    metadata:
      labels:
        app: dockercoins
        tier: worker
    spec:
      containers:
      - name: worker
        image: gitlab.orsys.fr:5050/brahimhamdi/dockercoins/worker:latest
---
apiVersion: v1
kind: Service
metadata:
  name: hasher
  labels:
    app: dockercoins
    tier: hasher
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
 selector:
   app: dockercoins
   tier: hasher
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: dockercoins
    tier: redis
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app: dockercoins
    tier: redis
---
apiVersion: v1
kind: Service
metadata:
  name: rng
  labels:
    app: dockercoins
    tier: rng
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: dockercoins
    tier: rng
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dockercoins
    tier: webui
  name: webui-svc
spec:
  type: NodePort
  selector:
    app: dockercoins
    tier: webui 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
