version: "3"
services:
  worker:
    image: brahimhamdi/worker:${TAG}
    #    build: ./worker
  rng:
    image: brahimhamdi/rng:${TAG}
    #    build: ./rng
  hasher:
    image: brahimhamdi/hasher:${TAG}
    #    build: ./hasher
  webui:
    image: brahimhamdi/webui:2.0
    ports:
      - "8000:80"
  redis:
    image: redis
